use customer_behaviour;
select * from mytable;


#--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from mytable
group by gender;


#--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from mytable
where discount_applied="Yes"
and purchase_amount > (select avg(purchase_amount) from mytable);


#-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avg_rating
from mytable
group by item_purchased
order by avg_rating desc
limit 5;

#--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2)
from mytable
where shipping_type in ("Standard" , "Express")
group by shipping_type;


#--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,sum(purchase_amount), avg(purchase_amount)
from mytable
group by subscription_status;



#--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


SELECT item_purchased, 
AVG(discount_applied = 'Yes') * 100 AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

#--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then "Returning"
else 'Loyal'
end as customer_segment
from mytable)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


#--Q8. What are the top 3 most purchased products within each category? 
 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;



 WITH ProductCounts AS (
    -- Step 1: Count purchases for each product within its category
    SELECT 
        category, 
        item_purchased, 
        COUNT(*) AS purchase_count
    FROM mytable
    GROUP BY category, item_purchased
),
RankedProducts AS (
    -- Step 2: Rank products within each category based on purchase count
    SELECT 
        category, 
        item_purchased, 
        purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY purchase_count DESC) AS product_rank
    FROM ProductCounts
)
-- Step 3: Select only the top 3 from each category
SELECT 
    category, 
    item_purchased, 
    purchase_count
FROM RankedProducts
WHERE product_rank <= 3
ORDER BY category, purchase_count DESC;
 




#--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;


#--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue desc;
